# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
        verbose: true
      - id: check-yaml

  - repo: local
    hooks:
      - id: run-spotless-format
        name: run spotless format-check
        language: system
        entry: bash -c 'cd kbazaar && make format-check'
        pass_filenames: false
        stages: [pre-commit]
