default_stages: [push]
repos:
  - repo: local
    hooks:
      - id: run-unit-tests
        name: run unit tests
        language: system
        entry: bash -c 'cd kbazaar && make test'
        pass_filenames: false
